
name: 'custom_sessions_project'
version: '1.0.0'
config-version: 2

profile: 'default'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  custom_sessions_project:
    # Sources
    snowplow__events_schema: 'atomic'
    snowplow__events_table: 'events'
    # Variables - Standard Config
    snowplow__start_date: "2023-01-01"
    # This is an example of session identifiers for BigQuery
    snowplow__bigquery_session_identifiers: [{"schema": "contexts_com_snowplowanalytics_session_identifier_2_*", "field": "session_identifier"}, {"schema": "contexts_com_snowplowanalytics_session_identifier_1_*", "field" : "session_id"}]
    # For Databricks
    snowplow__databricks_session_identifiers: [{"schema": "contexts_com_snowplowanalytics_session_identifier_2", "field": "session_identifier"}, {"schema": "contexts_com_snowplowanalytics_session_identifier_1", "field" : "session_id"}]
    # For Redshift/Postgres
    snowplow__rs_pg_session_identifiers: [{"schema": "contexts_com_snowplowanalytics_session_identifier_2", "field": "session_identifier", "prefix": "si_t", "alias": "sito"}, {"schema": "contexts_com_snowplowanalytics_session_identifier_1", "field" : "session_id", "prefix" : "si_o", "alias": "sido"}]
    # For Snowflake
    snowplow__snowflake_session_identifiers: [{"schema": "contexts_com_snowplowanalytics_session_identifier_2", "field": "sessionIdentifier"}, {"schema": "contexts_com_snowplowanalytics_session_identifier_1", "field" : "sessionId"}]

    snowplow__session_timestamp: 'collector_tstamp'
    snowplow__user_identifiers: [{"schema": "atomic", "field" : "domain_userid"}]
    snowplow__derived_tstamp_partitioned: true
    snowplow__days_late_allowed: 3
    snowplow__max_session_days: 3
    snowplow__backfill_limit_days: 30
    snowplow__app_id: []
    snowplow__allow_refresh: false
    snowplow__dev_target_name: dev
    snowplow__query_tag: 'snowplow_dbt'

models:
  custom_sessions_project:
    base:
      +materialized: 'table'
      +tags: 'snowplow_incremental'
