
name: 'braze_users_sync_project'
version: '1.0.0'
config-version: 2

profile: 'default'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  braze_users_sync_project:
    snowplow__braze_columns_to_include: [] # when left empty all columns will be kept (max 250), apart from values in columns_to_exclude, when populated, the columns_to_exclude will not get applied
    snowplow__braze_columns_to_exclude: ['user_identifier', 'model_tstamp'] # user_identifier == external_id in the sync
    snowplow__braze_column_based_sync: true

models:
  braze_users_sync_project:
    base:
      +materialized: 'table'
