
name: 'custom_users_project'
version: '1.0.0'
config-version: 2

profile: 'default'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  custom_users_project:
    # Sources
    snowplow__events_schema: 'atomic'
    snowplow__events_table: 'events'
    # Variables - Standard Config
    snowplow__start_date: "2023-01-01"
    snowplow__session_identifiers: [{"schema": "atomic", "field" : "domain_sessionid"}]
    snowplow__session_timestamp: 'collector_tstamp'
    # This is an example of user identifiers for BigQuery
    snowplow__bigquery_user_identifiers: [{"schema": "contexts_com_snowplowanalytics_user_identifier_2_*", "field" : "user_id"}, {"schema": "contexts_com_snowplowanalytics_user_identifier_1_*", "field" : "user_id"}]
    # For Databricks
    snowplow__databricks_user_identifiers: [{"schema": "contexts_com_snowplowanalytics_user_identifier_2", "field" : "user_id"}, {"schema": "contexts_com_snowplowanalytics_user_identifier_1", "field" : "user_id"}]
    # For Redshift/Postgres
    snowplow__rs_pg_user_identifiers: [{"schema": "contexts_com_snowplowanalytics_user_identifier_2", "field" : "user_id", "prefix" : "ui_t", "alias": "uidt"}, {"schema": "contexts_com_snowplowanalytics_user_identifier_1", "field" : "user_id", "prefix": "ui_o", "alias": "uido"}]
    # For Snowflake
    snowplow__snowflake_user_identifiers: [{"schema": "contexts_com_snowplowanalytics_user_identifier_2", "field" : "userId"}, {"schema": "contexts_com_snowplowanalytics_user_identifier_1", "field" : "userId"}]

    snowplow__derived_tstamp_partitioned: true
    snowplow__days_late_allowed: 3
    snowplow__max_session_days: 3
    snowplow__backfill_limit_days: 30
    snowplow__app_id: []
    snowplow__allow_refresh: false
    snowplow__dev_target_name: dev
    snowplow__query_tag: 'snowplow_dbt'

models:
  custom_users_project:
    base:
      +materialized: 'table'
      +tags: 'snowplow_incremental'
