
name: 'daily_aggregates_project'
version: '1.0.0'
config-version: 2

profile: 'default'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  daily_aggregates_project:
    # Sources
    snowplow__events_schema: atomic
    snowplow__events_table: events
    snowplow__events_database: snowplow
    snowplow__base_sessions: snowplow_base_sessions_this_run
    # Variables - Standard Config
    snowplow__start_date: "2023-01-01"
    # This is an example of session identifier being the date of the event
    snowplow__session_sql: "DATE(e.derived_tstamp)"
    snowplow__session_timestamp: collector_tstamp
    snowplow__user_identifiers: [{"schema": "atomic", "field" : "domain_userid"}]
    snowplow__derived_tstamp_partitioned: true
    snowplow__days_late_allowed: 3
    snowplow__max_session_days: 3
    snowplow__backfill_limit_days: 30
    snowplow__app_id: []
    snowplow__allow_refresh: false
    snowplow__dev_target_name: dev
    snowplow__query_tag: snowplow_dbt

# Completely or partially remove models from the manifest during run start.
on-run-start:
  - "{{ snowplow_utils.snowplow_delete_from_manifest(var('models_to_remove',[]), ref('snowplow_incremental_manifest')) }}"

# Update manifest table with last event consumed per sucessfully executed node/model
on-run-end:
  - "{{ snowplow_utils.snowplow_incremental_post_hook(package_name='daily_aggregates_project', incremental_manifest_table_name=var('snowplow__incremental_manifest', 'snowplow_incremental_manifest'), base_events_this_run_table_name='snowplow_base_events_this_run', session_timestamp=var('snowplow__session_timestamp')) }}"

models:
  daily_aggregates_project:
    base:
      +materialized: 'table'
      +tags: 'snowplow_incremental'
